### ISSUE TITLE
Some notification tests are broken

### ISSUE THREAD

**Issue by martinhoefling** [gopasspw/gopassbridge#56]
The output looks as follows:
```
  console.error node_modules/jest-plugin-unhandled-promise/build/install.js:1
    Error: expect(received).toEqual(expected)
    
    Expected value to equal:
      [{"iconUrl": "some-URL", "message": "this is just a test!", "title": "gopassbridge", "type": "basic"}]
    Received:
      [[{"iconUrl": "some-URL", "message": "this is just a test!", "title": "gopassbridge", "type": "basic"}]]
    
    Difference:
    
    - Expected
    + Received
    
      Array [
    +   Array [
          Object {
            "iconUrl": "some-URL",
            "message": "this is just a test!",
            "title": "gopassbridge",
            "type": "basic",
          },
    +   ],
      ]
        at generic.showNotificationOnSetting.then (/Users/martin/workspace/gopassbridge/tests/unit/generic.test.js:153:68)
        at <anonymous>

  console.error node_modules/jest-plugin-unhandled-promise/build/install.js:1
    Error: expect(received).toEqual(expected)
    
    Expected value to equal:
      0
    Received:
      1
        at generic.showNotificationOnSetting.then (/Users/martin/workspace/gopassbridge/tests/unit/generic.test.js:168:75)
        at <anonymous>
```

**Comment by martinhoefling** [comment]
Probably introduced in #52

**Comment by martinhoefling** [comment]
We actually forgot to return the promises, I'll fix this and the two tests.
